export var tabledata = [
  {
    FeedbackId: "R 2tul6ciy bb5GnW8",
    RecordDate: "5/24/2023 5:19",
    CustomerName: "Jason\nGrosvenor",
    CustomerEmail: "jgrosvenor@fuelexpres\ns.co.uk",
    NPS: 10,
    Atttiude: "Promoter",
    Category: "Application/Rejection",
    Product: "Banking service",
    Keywods: "aware, happening process",
    Insights: "Customer value being informed during the process",
    SuggestiveAction: "Maintain transparancy in process",
    FollowUpStatus: "NA",
    Action: "Follow",
  },
  {
    FeedbackId: "R_stmenvW6aARtA6I",
    RecordDate: " 5/23/2023 12:03",
    CustomerName: "Rishi Nühawan",
    CustomerEmail: "rishi.nijhawan@polym\nax.co.uk",
    NPS: 1,
    Atttiude: "Detractor",
    Category: "Account opening",
    Product: "HSBC net profile",
    Keywods: "9 weeks, account, HSBC net profile",
    Insights: "Customer expects faster account setup",
    SuggestiveAction: "Improve account setup speed",
    FollowUpStatus: "Processing",
    Action: "Follow",
  },
  {
    FeedbackId: "R_124QtqKalhijwkg",
    RecordDate: " 5/23/2023 11:46",
    CustomerName: "Pierre CORNET ",
    CustomerEmail: " pierrecornet@ubi-courtage.com",
    NPS: 3,
    Atttiude: "Detractor",
    Category: "Service performance",
    Product: "Banking service",
    Keywods: "staff, helpful, process, long",
    Insights: "Customer prefer faster and more efficient service",
    SuggestiveAction: "streamline process and reduce time",
    FollowUpStatus: "open",
    Action: "Follow",
  },
  {
    FeedbackId: "R_1ggtigtbMvac00y",
    RecordDate: "5/22/2023 7:57",
    CustomerName: "Debbie Colbert",
    CustomerEmail: "Debbie.Colbert@turckbanner.com",
    NPS: 4,
    Atttiude: "Detractor",
    Category: "Account opening",
    Product: "BACS setup",
    Keywods: "long processing time, frustrating",
    Insights: "customers value timely service delivery",
    SuggestiveAction: "Improve BACS setup processing time",
    FollowUpStatus: "closed",
    Action: "Follow",
  },
  {
    FeedbackId: "R 2s14pAlI\nHhb67i8",
    RecordDate: "4/27/2023 9.51",
    CustomerName: "Thomas Jahraus",
    CustomerEmail: "thomasjahraus@cidi.eu",
    NPS: 8,
    Atttiude: "Neutral",
    Category: "Account general",
    Product: "Service response time",
    Keywods: "response time, settings, contract data",
    Insights: "Urgent needs met, but slow updates",
    SuggestiveAction: "Improve response time",
    FollowUpStatus: "Processing",
    Action: "Follow",
  },
];
